# Generated by Django 3.2 on 2023-05-30 15:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('inputExample', models.TextField()),
                ('outputExample', models.TextField()),
                ('timeLimit', models.IntegerField()),
                ('memoryLimit', models.IntegerField()),
            ],
        ),
    ]
